config_type: simple_batch
job_parameters:
  time: "1-00:00:00"
  p: "cpu"
  body: "source ~/.bashrc\nconda activate power\n__launch__"
batch_name: gns_preprocess
dataset:
  datasets:
  - add_bus_type: false
    case_name: case118
    model: GNS
    name: pfdeltaGNS
    root_dir: data/pfdelta_data
    split: train
    task: _manual_list(1.1, 1.2, 1.3, 2.3)
  - add_bus_type: false
    case_name: case118
    model: GNS
    name: pfdeltaGNS
    root_dir: data/pfdelta_data
    split: val
    task: 1.3
functional:
  run_name: gns_preproces_%task
model:
  K: 15
  gamma: 0.1
  hidden_dim: 20
  name: graph_neural_solver
