config_type: simple_batch
job_parameters:
  time: "1-00:00:00"
  p: "cpu"
  body: "source ~/.bashrc\nconda activate power\n__launch__"
batch_name: pfnet_data_preprocess
model:
  K: 3
  dropout_rate: 0.2
  efeature_dim: 5
  hidden_dim: 256
  n_gnn_layers: 4
  name: powerflownet
  nfeature_dim: 6
  output_dim: 6
dataset:
  datasets:
  - add_bus_type: false
    case_name: case118
    model: PFNet
    name: pfdeltaPFNet
    root_dir: data/pfdelta_data
    split: train
    task: _manual_list(1.1, 1.2, 1.3, 2.3)
  - add_bus_type: false
    case_name: case118
    model: PFNet
    name: pfdeltaPFNet
    root_dir: data/pfdelta_data
    split: val
    task: 1.3
functional:
  run_name: pfnet_data_preprocessing%task
