data_dir = "/home/akrivera/orcd/scratch/pfdelta_data"
case_name = "case14"
topology_perturb = "n-2"

delete_intermediate = true
analysis_mode = false

[matlab]
# Note: Code has only been tested on this MATLAB version
# TODO: you need to add info here on which matpower version should be used too.
# TODO: add note on intel matlab only for mac
# TODO: add note to leave empty on cluster
home = ""
matpower_path = "/orcd/home/002/akrivera/third_party/matpower/matpower8_1/"
