data_dir = "data"
case_name = "case2000"
topology_perturb = "n-1"

delete_intermediate = true
analysis_mode = false

[matlab]
# Note: Code has only been tested on this MATLAB version
# TODO: you need to add info here on which matpower version should be used too.
# TODO: add note on intel matlab only for mac
# TODO: add note to leave empty on cluster
home = "C:\\Program Files\\MATLAB\\R2023b"
matpower_path = "C:\\matpower8.1\\matpower8.1"