config_type: experiment
model:
  name: canos_opf
  dataset: _include_ 
  edge_feat_dim: 128
  node_feat_dim: 128
  hidden_dim: 128
  include_sent_messages: True
  k_steps: 48
dataset:
  datasets:
  - name: opfdata
  - name: opfdata
optim:
  optimizer:
    name: "Adam"
    lr: 0.0002
    weight_decay: 0.
  lr_scheduler:
    name: SequentialLR
    milestones:
    - 10000
    schedulers:
    - name: LinearLR
      start_factor: 0.0001
      end_factor: 1
    - name: StepLR
      gamma: 0.9
      step_size: 4000
  train_params:
    # epochs: 5
    train_steps: 600000
    batch_size: 32
    train_loss:
    - MSELoss
  val_params:
    report_every: 422
    batch_size: 64
    high_is_good: True
    val_loss:
    - MSELoss
functional:
  trainer_name: gnn_trainer
  run_name: mytest
  run_location: tutorial_runs/one_experiment
