config_type: experiment
model:
  name: canos_opf
  dataset: _include_ 
  edge_feat_dim: 128
  node_feat_dim: 128
  hidden_dim: 128
  include_sent_messages: True
  k_steps: 48
dataset:
  datasets:
  - name: opfdata
  - name: opfdata
optim:
  optimizer:
    name: "Adam"
    lr: 0.001
    weight_decay: 0.
  train_params:
    epochs: 5
    batch_size: 256
    train_loss:
    - CrossEntropyLoss # First is for training
    - ClassificationAccuracy # Rest are for tracking
  val_params:
    report_every: 3 # How often to calculate val error
    batch_size: 256
    high_is_good: True
    val_loss:
    - ClassificationAccuracy # First used for best model
    - CrossEntropyLoss # Rest are for tracking
functional:
  trainer_name: gnn_trainer
  run_name: mytest
  run_location: tutorial_runs/one_experiment
