config_type: experiment
model:
  name: canos_opf
  dataset: _include_
  hidden_dim: 128
  include_sent_messages: True
  k_steps: 16
dataset:
  datasets:
  - name: opfdata
    num_groups: 1 # SCALE THIS
    # force_reload: True
  - name: opfdata
    split: val
    num_groups: 1
  topological_perturbations: True
  pre_transform: mean_zero_variance_one
  case_name: pglib_opf_case500_goc
optim:
  optimizer:
    name: "Adam"
    lr: 0.0005
    weight_decay: 0.
  lr_scheduler:
    name: SequentialLR
    milestones:
    - 250 # SCALE THIS
    schedulers:
    - name: LinearLR
      start_factor: 0.01
      end_factor: 1
    - name: StepLR
      gamma: 0.8
      step_size: 1000 # SCALE THIS
  train_params:
    # epochs: 5
    train_steps: 21100 # SCALE THIS
    batch_size: 64
    train_loss:
    - name: combined_loss
      loss1: canos_mse
      loss2: opf_constraint_violation
      lamb: 0.1
    - name: recycle_loss
      recycled_parameter: constraint_loss
      keyword: constraint_violation
      loss_name: Total Constraint Violation
    - name: recycle_loss
      recycled_parameter: bus_real_mismatch
      keyword: constraint_violation
      loss_name: Bus Real Mismatch
    - name: recycle_loss
      recycled_parameter: bus_reactive_mismatch
      keyword: constraint_violation
      loss_name: Bus Reactive Mismatch
    - name: recycle_loss
      recycled_parameter: angle_difference_violations
      keyword: constraint_violation
      loss_name: Angle Diff. Violation
    - name: recycle_loss
      recycled_parameter: voltage_violations
      keyword: constraint_violation
      loss_name: Voltage Violation
    - name: recycle_loss
      recycled_parameter: real_flow_mismatch_violation
      keyword: constraint_violation
      loss_name: Real Flow Mismatch
    - name: recycle_loss
      recycled_parameter: imag_flow_mismatch_violation
      keyword: constraint_violation
      loss_name: Reactive Flow Mismatch
    - name: recycle_loss
      recycled_parameter: generator_pg_violations
      keyword: constraint_violation
      loss_name: Pg Violation
    - name: recycle_loss
      recycled_parameter: generator_qg_violations
      keyword: constraint_violation
      loss_name: Qg Violation
    - name: recycle_loss
      recycled_parameter: branch_flow_violation_f
      keyword: constraint_violation
      loss_name: Branch Flow Fwd Violation
    - name: recycle_loss
      recycled_parameter: branch_flow_violation_r
      keyword: constraint_violation
      loss_name: Branch Flow Rev Violation
    - name: recycle_loss
      recycled_parameter: total_loss
      keyword: canos_mse
      loss_name: Total MSE
    - name: recycle_loss
      recycled_parameter: va
      keyword: canos_mse
      loss_name: VA MSE
    - name: recycle_loss
      recycled_parameter: vm
      keyword: canos_mse
      loss_name: VM MSE
    - name: recycle_loss
      recycled_parameter: pg
      keyword: canos_mse
      loss_name: PQ MSE
    - name: recycle_loss
      recycled_parameter: qg
      keyword: canos_mse
      loss_name: QG MSE
    - name: recycle_loss
      recycled_parameter: pt_ac
      keyword: canos_mse
      loss_name: PT AC MSE
    - name: recycle_loss
      recycled_parameter: qt_ac
      keyword: canos_mse
      loss_name: QT AC MSE
    - name: recycle_loss
      recycled_parameter: pf_ac
      keyword: canos_mse
      loss_name: PF AC MSE
    - name: recycle_loss
      recycled_parameter: qf_ac
      keyword: canos_mse
      loss_name: QF AC MSE
    - name: recycle_loss
      recycled_parameter: pt_transformer
      keyword: canos_mse
      loss_name: PT Tr. MSE
    - name: recycle_loss
      recycled_parameter: qt_transformer
      keyword: canos_mse
      loss_name: QT Tr. MSE
    - name: recycle_loss
      recycled_parameter: pf_transformer
      keyword: canos_mse
      loss_name: PF Tr. MSE
    - name: recycle_loss
      recycled_parameter: qf_transformer
      keyword: canos_mse
      loss_name: QF Tr. MSE
  val_params:
    report_every: 211 # 8438 # SCALE THIS
    batch_size: 64
    val_loss:
    - name: combined_loss
      loss1: canos_mse
      loss2: opf_constraint_violation
      lamb: 0.1
    - name: recycle_loss
      recycled_parameter: constraint_loss
      keyword: constraint_violation
      loss_name: Total Constraint Violation
    - name: recycle_loss
      recycled_parameter: bus_real_mismatch
      keyword: constraint_violation
      loss_name: Bus Real Mismatch
    - name: recycle_loss
      recycled_parameter: bus_reactive_mismatch
      keyword: constraint_violation
      loss_name: Bus Reactive Mismatch
    - name: recycle_loss
      recycled_parameter: angle_difference_violations
      keyword: constraint_violation
      loss_name: Angle Diff. Violation
    - name: recycle_loss
      recycled_parameter: voltage_violations
      keyword: constraint_violation
      loss_name: Voltage Violation
    - name: recycle_loss
      recycled_parameter: real_flow_mismatch_violation
      keyword: constraint_violation
      loss_name: Real Flow Mismatch
    - name: recycle_loss
      recycled_parameter: imag_flow_mismatch_violation
      keyword: constraint_violation
      loss_name: Reactive Flow Mismatch
    - name: recycle_loss
      recycled_parameter: generator_pg_violations
      keyword: constraint_violation
      loss_name: Pg Violation
    - name: recycle_loss
      recycled_parameter: generator_qg_violations
      keyword: constraint_violation
      loss_name: Qg Violation
    - name: recycle_loss
      recycled_parameter: branch_flow_violation_f
      keyword: constraint_violation
      loss_name: Branch Flow Fwd Violation
    - name: recycle_loss
      recycled_parameter: branch_flow_violation_r
      keyword: constraint_violation
      loss_name: Branch Flow Rev Violation
    - name: recycle_loss
      recycled_parameter: total_loss
      keyword: canos_mse
      loss_name: Total MSE
    - name: recycle_loss
      recycled_parameter: va
      keyword: canos_mse
      loss_name: VA MSE
    - name: recycle_loss
      recycled_parameter: vm
      keyword: canos_mse
      loss_name: VM MSE
    - name: recycle_loss
      recycled_parameter: pg
      keyword: canos_mse
      loss_name: PQ MSE
    - name: recycle_loss
      recycled_parameter: qg
      keyword: canos_mse
      loss_name: QG MSE
    - name: recycle_loss
      recycled_parameter: pt_ac
      keyword: canos_mse
      loss_name: PT AC MSE
    - name: recycle_loss
      recycled_parameter: qt_ac
      keyword: canos_mse
      loss_name: QT AC MSE
    - name: recycle_loss
      recycled_parameter: pf_ac
      keyword: canos_mse
      loss_name: PF AC MSE
    - name: recycle_loss
      recycled_parameter: qf_ac
      keyword: canos_mse
      loss_name: QF AC MSE
    - name: recycle_loss
      recycled_parameter: pt_transformer
      keyword: canos_mse
      loss_name: PT Tr. MSE
    - name: recycle_loss
      recycled_parameter: qt_transformer
      keyword: canos_mse
      loss_name: QT Tr. MSE
    - name: recycle_loss
      recycled_parameter: pf_transformer
      keyword: canos_mse
      loss_name: PF Tr. MSE
    - name: recycle_loss
      recycled_parameter: qf_transformer
      keyword: canos_mse
      loss_name: QF Tr. MSE
functional:
  trainer_name: gnn_trainer
