config_type: experiment
dataset:
  datasets:
  - add_bus_type: true
    case_name: case118_seeds
    model: CANOS
    name: pfdeltaCANOS
    root_dir: ../../hf_pfdelta_data
    split: train
    task: 1.3
  - add_bus_type: true
    case_name: case118_seeds
    model: CANOS
    name: pfdeltaCANOS
    root_dir: ../../hf_pfdelta_data
    split: val
    task: 1.3
functional:
  config: canos_pf_jobs
  cpu: false
  is_debug: false
  run_location: runs/canos_pf_task_1_3/canos_pf_hd128_depth15_lr5e-4_seed11_0_250510_134237/canos_pf_hd128_depth15_lr5e-4_seed11_0_250510_134237_250711_195502
  run_name: canos_pf_hd128_depth15_lr5e-4_seed11_0_250510_134237_250711_195502
  seed: 11
  # slurm_jobid: '3512836'
  trainer_name: gnn_trainer
model:
  dataset: _include_
  hidden_dim: 128
  include_sent_messages: true
  k_steps: 15
  name: canos_pf
optim:
  lr_scheduler:
    milestones:
    - 5
    name: SequentialLR
    schedulers:
    - end_factor: 1
      name: LinearLR
      start_factor: 0.01
    - gamma: 0.9
      name: StepLR
      step_size: 4
  optimizer:
    lr: 0.0005
    name: Adam
    weight_decay: 0.0
  train_params:
    batch_size: 64
    epochs: 50
    train_loss:
    - lamb: 0
      loss1: canos_pf_mse
      loss2: pf_constraint_violation
      name: combined_loss
      output_name: canos_pf_mse_only
    - model: CANOS
      name: universal_power_balance
  val_params:
    batch_size: 64
    early_stop:
      decrease_by: 0.01
      decrease_for: 10
      needs_best_every: 15
    report_every: 2
    val_loss:
    - lamb: 0
      loss1: canos_pf_mse
      loss2: pf_constraint_violation
      name: combined_loss
      output_name: canos_pf_mse_only
    - lamb: 1
      loss1: canos_pf_mse
      loss2: pf_constraint_violation
      name: combined_loss
    - model: CANOS
      name: universal_power_balance
