config_type: simple_batch
job_parameters:
  time: "03:00:00"
  p: "cpu-gpu-rtx8000"
  gpus: 1
  body: "__launch__"
batch_name: graphconv_test2_varySeedsLR
dataset:
  datasets:
  - add_bus_type: true
    case_name: case118_seeds
    model: PFNet
    name: pfdeltaPFNet
    root_dir: ../../hf_pfdelta_data
    split: train
    task: 1.3
    transform: pfnet_data_mean0_var1
  - add_bus_type: true
    case_name: case118_seeds
    model: PFNet
    name: pfdeltaPFNet
    root_dir: ../../hf_pfdelta_data
    split: val
    task: 1.3
    transform: pfnet_data_mean0_var1
functional:
  config: graph_conv
  cpu: false
  is_debug: false
  run_location: runs/graph_conv_task_1_3/
  run_name: graphconv_hd_512_layers_16_seed%seed_lr%lr_bestByMSE
  seed: _manual_list(11, 22, 33 | 11, 22, 33)
  trainer_name: gnn_trainer
model:
  in_dim: 6
  hidden_dim: 512
  out_dim: 6
  n_layers: 16
  name: graph_conv
optim:
  optimizer:
    lr: _manual_list(0.001, 0.0001, 0.0005 | 1e-3, 1e-4, 5e-4)
    name: Adam
  train_params:
    batch_size: 64
    epochs: 100
    train_loss:
    - name: GNNTorchLoss
      output_name: bus__y
      torch_nn_name: MSELoss
    - name: pfn_masked_mse
      regularize: false
    - name: pfn_masked_mse
      regularize: true
    - model: PFNet
      name: universal_power_balance
    - keyword: pbl_pf
      loss_name: PBL Max
      name: recycle_loss
      recycled_parameter: power_balance_max
    - keyword: pbl_pf
      loss_name: PBL L2
      name: recycle_loss
      recycled_parameter: power_balance_l2
  val_params:
    batch_size: 64
    early_stop:
      decrease_by: 0.01
      decrease_for: 10
      needs_best_every: 15
    report_every: 5
    val_loss:
    - name: GNNTorchLoss
      output_name: bus__y
      torch_nn_name: MSELoss
    - model: PFNet
      name: universal_power_balance
    - name: pfn_masked_mse
      regularize: false
    - name: pfn_masked_mse
      regularize: true
    - keyword: pbl_pf
      loss_name: PBL Max
      name: recycle_loss
      recycled_parameter: power_balance_max
    - keyword: pbl_pf
      loss_name: PBL L2
      name: recycle_loss
      recycled_parameter: power_balance_l2