config_type: experiment
dataset:
  datasets:
  - add_bus_type: false
    case_name: case14_seeds
    model: PFNet
    name: pfdeltaPFNet
    root_dir: data/pfdelta_data
    split: train
    task: 1.3
    transform: pfnet_data_mean0_var1
  - add_bus_type: false
    case_name: case14_seeds
    model: PFNet
    name: pfdeltaPFNet
    root_dir: data/pfdelta_data
    split: val
    task: 1.3
    transform: pfnet_data_mean0_var1
functional:
  config: powerflownet
  cpu: false
  is_debug: false
  run_location: runs/pfnet_task_2_3/pfnet_hd256_lr5e-4_layers_4_K_3_seed11_0_250513_214924
  run_name: pfnet_hd256_lr5e-4_layers_4_K_3_seed11_0_250513_214924
  seed: 11
  trainer_name: gnn_trainer
model:
  K: 3
  dropout_rate: 0.2
  efeature_dim: 5
  hidden_dim: 256
  n_gnn_layers: 4
  name: powerflownet
  nfeature_dim: 6
  output_dim: 6
optim:
  optimizer:
    lr: 0.0005
    name: Adam
  train_params:
    batch_size: 64
    epochs: 100
    train_loss:
    - name: GNNTorchLoss
      output_name: bus__y
      torch_nn_name: MSELoss
    - name: pfn_masked_mse
      regularize: false
    - name: pfn_masked_mse
      regularize: true
    - model: PFNet
      name: universal_power_balance
    - keyword: pbl_pf
      loss_name: PBL Max
      name: recycle_loss
      recycled_parameter: power_balance_max
    - keyword: pbl_pf
      loss_name: PBL L2
      name: recycle_loss
      recycled_parameter: power_balance_l2
  val_params:
    batch_size: 64
    early_stop:
      decrease_by: 0.01
      decrease_for: 10
      needs_best_every: 15
    report_every: 5
    val_loss:
    - name: pfn_masked_mse
      regularize: false
    - name: pfn_masked_mse
      regularize: true
    - name: GNNTorchLoss
      output_name: bus__y
      torch_nn_name: MSELoss
    - model: PFNet
      name: universal_power_balance
    - keyword: pbl_pf
      loss_name: PBL Max
      name: recycle_loss
      recycled_parameter: power_balance_max
    - keyword: pbl_pf
      loss_name: PBL L2
      name: recycle_loss
      recycled_parameter: power_balance_l2
