config_type: experiment
dataset:
  datasets:
  - add_bus_type: false
    case_name: case118_seeds
    model: GNS
    name: pfdeltaGNS
    root_dir: data/pfdelta_data
    split: train
    task: 1.3
  - add_bus_type: false
    case_name: case118_seeds
    model: GNS
    name: pfdeltaGNS
    root_dir: data/pfdelta_data
    split: val
    task: 1.3
functional:
  config: gns_jobs
  cpu: false
  is_debug: false
  run_location: runs/gns_task_1_3/gns_K15_hd20_gamma0.1_lr1e-3_seed11_0_250510_134452
  run_name: gns_K15_hd20_gamma0.1_lr1e-3_seed11_0_250510_134452
  seed: 11
  trainer_name: gnn_trainer
model:
  K: 15
  gamma: 0.1
  hidden_dim: 20
  name: graph_neural_solver
optim:
  optimizer:
    lr: 0.001
    name: Adam
  train_params:
    batch_size: 64
    epochs: 20
    train_loss:
    - name: gns_layer_loss
    - name: gns_last_loss
    - model: GNS
      name: universal_power_balance
  val_params:
    batch_size: 64
    early_stop:
      decrease_by: 0.01
      decrease_for: 10
      needs_best_every: 15
    report_every: 2
    val_loss:
    - name: gns_layer_loss
    - name: gns_last_loss
    - model: GNS
      name: universal_power_balance
