config_type: simple_batch
batch_name: gns_task_1_1
job_parameters:
  time: "10:00:00"
  p: "cpu-gpu-v100"
  gpus: 1
  body: "source ~/.bashrc\nconda activate pfdelta\n__launch__"
model:
  name: graph_neural_solver
  K:  15
  hidden_dim: 20
  gamma: 0.1
dataset:
  datasets:
  - name: pfdeltaGNS
    root_dir: data/pfdelta_data
    case_name: case118_seeds
    split: train
    model: GNS
    task: 1.1
    add_bus_type: False 
  - name: pfdeltaGNS
    root_dir: data/pfdelta_data
    case_name: case118_seeds
    split: val
    model: GNS
    task: 1.1
    add_bus_type: False 
optim:
  optimizer:
    lr: 0.001
  train_params:
    epochs: 20
    batch_size: 64
    train_loss:
    - name: gns_layer_loss
    - name: gns_last_loss
    - name: universal_power_balance
      model: GNS
  val_params:
    early_stop:
      decrease_for: 10 # Needs to be a divisor of report_every
      decrease_by: 0.01
      needs_best_every: 15
    report_every: 2
    batch_size: 64
    val_loss:
    - name: gns_layer_loss
    - name: gns_last_loss
    - name: universal_power_balance
      model: GNS
functional:
  trainer_name: gnn_trainer
  seed: _manual_list(11, 22, 33 | 11, 22, 33)
  run_location: gns_task_1_1
  run_name: gns_K15_hd20_gamma0.1_lr1e-3_seed%seed

# jobs:
# - functional:
#     trainer_name: gnn_trainer