config_type: batch
job_parameters:
  time: "12:00:00"
  p: "cpu-gpu-v100"
  gpus: 1
  body: "source ~/.bashrc\nconda activate pfdelta\n__launch__"
default_values:
  model:
    name: graph_neural_solver
    K: _manual_list(30, 15 | 30, 15)
    hidden_dim: _manual_list(10, 20 | 10, 20)
    gamma: _manual_list(0.1, 0.5 | 0.1, 0.5)
  dataset:
    datasets:
    - split: train
    - split: val
    name: pfdeltaGNS
    root_dir: data/pfdelta_data
    case_name: case118_seeds
    task: 1.3
    add_bus_type: False 
  optim:
    optimizer:
      lr: _manual_list(0.0005 | 5e-4)
    train_params:
      epochs: 30
      batch_size: 64
      train_loss:
      - gns_layer_loss
      - gns_last_loss
    val_params:
      early_stop:
        decrease_for: 10 # Needs to be a divisor of report_every
        decrease_by: 0.01
        needs_best_every: 15
      report_every: 5
      batch_size: 64
      val_loss:
      - gns_layer_loss
      - gns_last_loss
  functional:
    seed: 11
    run_location: gns_hyperparam_tuning
    run_name: gns_K%K_hd%hidden_dim_gamma%gamma_lr%lr

jobs:
- functional:
    trainer_name: gnn_trainer