config_type: simple_batch # TODO: change this to "experiment" and comment out job_parameters to run locally
job_parameters: # TODO: update as needed
  time: "1-00:00:00"
  p: "cpu-gpu-v100"
  gpus: 1
  body: "source ~/.bashrc\nconda activate pfdelta\n__launch__" # TODO: update conda env name
batch_name: pfnet_task_2_3
model:
  K: 4
  n_gnn_layers: 5
  dropout_rate: 0.2
  efeature_dim: 5
  hidden_dim: 256
  name: powerflownet
  nfeature_dim: 6
  output_dim: 6
dataset:
  datasets:
  - add_bus_type: false
    case_name: case118
    model: PFNet
    name: pfdeltaPFNet
    root_dir: data/pfdelta_data # TODO: update root_dir if needed
    split: train
    task: 2.3
    transform: pfnet_data_mean0_var1
  - add_bus_type: false
    case_name: case118
    model: PFNet
    name: pfdeltaPFNet
    root_dir: data/pfdelta_data
    split: val
    task: 2.3
    transform: pfnet_data_mean0_var1
functional:
  trainer_name: gnn_trainer
  run_name: pfnet_K4_layers5_hd256_lr1e-4_task2_3
  run_location: pfnet_task_2_3
  seed: 11
optim:
  optimizer:
    lr: 0.0001
    name: Adam
  train_params:
    batch_size: 64
    epochs: 100
    train_loss:
    - name: GNNTorchLoss
      output_name: bus__y
      torch_nn_name: MSELoss
    - name: pfn_masked_mse
      regularize: false
    - name: pfn_masked_mse
      regularize: true
    - model: PFNet
      name: universal_power_balance
    - keyword: pbl_pf
      loss_name: PBL Max
      name: recycle_loss
      recycled_parameter: power_balance_max
    - keyword: pbl_pf
      loss_name: PBL L2
      name: recycle_loss
      recycled_parameter: power_balance_l2
  val_params:
    batch_size: 64
    early_stop:
      decrease_by: 0.01
      decrease_for: 10
      needs_best_every: 15
    report_every: 2
    val_loss:
    - name: pfn_masked_mse
      regularize: false
    - name: pfn_masked_mse
      regularize: true
    - name: GNNTorchLoss
      output_name: bus__y
      torch_nn_name: MSELoss
    - model: PFNet
      name: universal_power_balance
    - keyword: pbl_pf
      loss_name: PBL Max
      name: recycle_loss
      recycled_parameter: power_balance_max
    - keyword: pbl_pf
      loss_name: PBL L2
      name: recycle_loss
      recycled_parameter: power_balance_l2
