config_type: batch
batch_name: pfnet_task_seed_sweep
job_parameters:
  time: "18:00:00"
  p: "cpu-gpu-v100"
  gpus: 1
  body: "source ~/.bashrc\nconda activate pfdelta\n__launch__"
default_values:
  config: powerflownet
  model:
    hidden_dim: 256
    n_gnn_layers: 4
    K: 3
  optim:
    optimizer:
      lr: 0.0005
  functional:
    seed: _manual_list(11, 22, 33 | 11, 22, 33)

jobs:
- functional:
    run_name: pfnet_hd256_lr5e-4_layers4_K3_seed%seed
    run_location: pfn_exps/pfn_task1.1_seeds
  dataset:
    task: 1.1

- functional:
    run_name: pfnet_hd256_lr5e-4_layers4_K3_seed%seed
    run_location: pfn_exps/pfn_task1.2_seeds
  dataset:
    task: 1.2

- functional:
    run_name: pfnet_hd256_lr5e-4_layers4_K3_seed%seed
    run_location: pfn_exps/pfn_task1.3_seeds
  dataset:
    task: 1.3
