config_type: batch
batch_name: pfnet_hyperparam_tuning
job_parameters:
  time: "18:00:00"
  p: "cpu-gpu-v100"
  gpus: 1
  body: "source ~/.bashrc\nconda activate pfdelta\n__launch__"
default_values:
  config: powerflownet
  model:
    hidden_dim: _manual_list(128, 256 | 128, 256)
  optim:
    optimizer:
      lr: _manual_list(0.001, 0.0005 | 1e-3, 5e-4)
  functional:
    run_location: pfn_118

jobs:
- model:
    n_gnn_layers: 4
    K: 3
  functional:
    run_name: pfnet_hd%hd256_lr%lr1e-3_layers_4_K_3

- model:
    n_gnn_layers: 5
    K: 4
  functional:
    run_name: pfnet_hd%hd256_lr%lr1e-3_layers_5_K_4