config_type: batch
job_parameters:
  time: "12:00:00"
  p: "cpu-gpu-v100"
  gpus: 1
  body: "source ~/.bashrc\nconda activate power\n__launch__"
default_values:
  model:
    name: powerflownet
    nfeature_dim: 6
    efeature_dim: 5
    output_dim: 6
    hidden_dim: _manual_list(64, 128, 256 | 64, 128, 256)
    # n_gnn_layers: 4
    # K: 3
    dropout_rate: 0.2
  dataset:
    datasets:
    - split: train
    - split: val
    name: pfdeltaPFNet
    root_dir: data/pfdelta_data
    case_name: case118_seeds
    task: 1.3
    pre_transform: pfnet_data_mean0_var1
    # force_reload: true
  optim:
    optimizer:
      lr: _manual_list(0.001, 0.0005 | 1e-3, 5e-4)
    train_params:
      batch_size: 64
      epochs: 250
      train_loss:
      - name: GNNTorchLoss
        torch_nn_name: MSELoss
        output_name: "bus__y"
      - name: pfn_masked_mse
        regularize: False
      - name: pfn_masked_mse
        regularize: True
    val_params:
      batch_size: 64
      report_every: 5
      val_loss:
      - name: pfn_masked_mse
        regularize: False
      - name: pfn_masked_mse
        regularize: True
      - name: GNNTorchLoss
        torch_nn_name: MSELoss
        output_name: "bus__y"
  functional:
    trainer_name: gnn_trainer
    seed: 11
    run_location: powerflow_case118

jobs:
- model:
    n_gnn_layers: 4
    K: 3
  functional:
    run_name: pfn_lr%lr_hd%hidden_dim_depth4_k3

- model:
    n_gnn_layers: 5
    K: 4
  functional:
    run_name: pfn_lr%lr_hd%hidden_dim_depth5_k4