config_type: simple_batch
job_parameters:
  time: "1-00:00:00"
  p: "cpu"
  body: "source ~/.bashrc\nconda activate power\n__launch__"
batch_name: canos_preprocess
dataset:
  datasets:
  - add_bus_type: true
    case_name: case118
    model: CANOS
    name: pfdeltaCANOS
    root_dir: data/pfdelta_data
    split: train
    task: _manual_list(1.1, 1.2, 1.3, 2.3)
  - add_bus_type: true
    case_name: case118
    model: CANOS
    name: pfdeltaCANOS
    root_dir: data/pfdelta_data
    split: val
    task: 1.3
functional:
  run_name: canos_preprocess_%task
model:
  dataset: _include_
  hidden_dim: 128
  include_sent_messages: true
  k_steps: 15
  name: canos_pf
